### ISSUE TITLE
Add RADIUS code 12

### ISSUE THREAD

**Issue by doug-fsu** [frontporch/Radius.NET#12]
Would you consider adding:
    STATUS_SERVER = 12,
as one of the enumerated RADIUS codes
at line 16 of Radius.NET?

Code 12 is shown as "experimental"
in RFC 2865 and gets a full treatment
in RFC 5997.
Your RADIUS client is used by PRTG and a sensor
that made use of a Status-Server code
would make for a very light-weight sensor.

**Comment by spowser** [comment]
Thanks for your input.  That seems like a small change and after looking at the RFC doesn't appear too complex.  Is there a time frame you are looking to have this by?
Shane

Date: Mon, 22 Aug 2016 05:58:56 -0700

**Comment by doug-fsu** [comment]
Shane -

Thanks so much for your reply.
There is no urgency.  I am trying to get the folks at PRTG to update their RADIUS sensor so that it will query the FreeRADIUS Status Server.  They rely on your client so I'm on hold with them until your client supports STATUS_SERVER.  It would be nice if it was convenient for you to do it sometime before the end of September but again, this is a "nice to have" issue.  I appreciate your consideration.

Doug Wussler
Florida State University

**Comment by spowser** [comment]
A new version of RADIUS.NET has been uploaded to NuGet with this change.

https://www.nuget.org/packages/Radius/2.0.0

**Comment by doug-fsu** [comment]
Shane - Wow, thanks much.  Really appreciate it.  Now if I can just get PRTG to move....


Doug

________________________________
