### ISSUE TITLE
Access_accept but did not Console.WriteLink Accepted

### ISSUE THREAD

**Issue by dhpark21** [frontporch/Radius.NET#6]
Hi.
when Auth but did not console write Accept
also, when Auth fail then write Reject   hope.
Thanks

**Comment by spowser** [comment]
Do you have code that replicates the issue you are seeing?

**Comment by dhpark21** [comment]
my code is  this
===
using System;
using System.Collections.Generic;
using System.Linq;
using FP.Radius;
using System.Text;
using System.Threading.Tasks;

namespace ClientTest
{
	internal class Program
	{
		private static void Main(string[] args)
		{
			//if (args.Length != 4)
			//{
			//	ShowUsage();
			//	return;
			//}

			Authenticate(args).ContinueWith(task => 
			{
				if (task.IsFaulted)
					Console.WriteLine("Error : " + task.Exception.Message);
			});

		}

		private async static Task Authenticate(string[] args)
		{

			RadiusClient rc = new RadiusClient(args[0], args[1]);
			RadiusPacket authPacket = rc.Authenticate(args[2], args[3]);
            authPacket.SetAttribute(new VendorSpecificAttribute(10135, 1, UTF8Encoding.UTF8.GetBytes("Testing")));
			authPacket.SetAttribute(new VendorSpecificAttribute(10135, 2, new[] { (byte)7 }));
			RadiusPacket receivedPacket = await rc.SendAndReceivePacket(authPacket);

            if (receivedPacket == null) throw new Exception("Can't contact remote radius server !");

            switch (receivedPacket.PacketType)
			{
				case RadiusCode.ACCESS_ACCEPT:
					Console.WriteLine("Accepted");
					foreach (var attr in receivedPacket.Attributes)
						Console.WriteLine(attr.Type.ToString() + " = " + attr.Value);
					break;
				case RadiusCode.ACCESS_CHALLENGE:
					Console.WriteLine("Challenged");
					break;
				default:
					Console.WriteLine("Rejected");
					break;
			}
		}

		private static void ShowUsage()
		{
			Console.WriteLine("Usage : ClientTest.exe hostname sharedsecret username password");
		}
	}
}
===
Windows 7 32bit .net:4.5.1
Thanks

**Comment by spowser** [comment]
I ran your code which looks to be the same as the sample against our RADIUS server and everything is working as expected.  Make sure you have the proper secret configured or you will not receive a rejected message.  I have identified some things we could do to make it more obvious when the secret is wrong and will be looking into that.

**Comment by jeernest** [comment]
We have the same issue with the example on two different machines. I have Windows 7 Enterprise SP 1 64 bit. I tried to debug, but it fails unexpectedly without any exception.

**Comment by jeernest** [comment]
We found the problem. The example has a bug. The Main() method doesn't wait for finishing the Authenticate() call. It immediately exits and shuts down the worker threads too. There's missing something like:
var authTask=Authenticate(args);
authTask.Wait();
The library itself works correctly.

**Comment by spowser** [comment]
We just checked in some code that should resolve this issue.  The packet will now be returned regardless if the secret is correct or not.  We also added the .Wait() call to the example so it will not exit without allowing the other threads to finish.
